### ISSUE TITLE
Unable to launch editor: "No module named 'pman_renderer'"

### ISSUE THREAD

**Issue by Kupoman** [Moguri/gestalt-editor#9]
After installing the packages in requirement.txt and running `python main.py`, I get the following error:

```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Starting build
warning: could not find asset directory: /home/daniel/source/gestalt-editor/assets/
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    main()
  File "main.py", line 34, in main
    app = GameApp()
  File "main.py", line 18, in __init__
    pman.shim.init(self)
  File "/home/daniel/source/gestalt-editor/venv/lib/python3.7/site-packages/pman/shim.py", line 21, in init
    pman.create_renderer(base, config)
  File "/home/daniel/source/gestalt-editor/venv/lib/python3.7/site-packages/pman/core.py", line 220, in create_renderer
    import pman_renderer #pylint: disable=import-error
ModuleNotFoundError: No module named 'pman_renderer'
```

**Comment by Moguri** [comment]
This is fixed upstream in pman. We'll get the fix when pman gets a release.
